import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react"; // Added useState and useEffect hooks
import classes from "@/styles/Home.module.scss";
import TechStackList from "@/components/layout/techStackList/TechStackList";

export default function Home() {
  const [isAnimated, setIsAnimated] = useState(false);

  useEffect(() => {
    setIsAnimated(true);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
      </Head>
      <main className={classes.main}>
        <div className={classes.mainWrapper}>
          <section
            className={`${classes.left} ${
              isAnimated && classes.animationSlideFromLeft
            }`}
          >
            <h1 className={classes.heading}>
              <em>
                Hi, welcome! My name is{" "}
                <span className={classes.headingSpan}>
                  Hubert<span className={classes.headingSpanAfter}>Hubert</span>
                </span>
                , and I might be what you are looking for.
              </em>
            </h1>
          </section>
          <div className={classes.imgWrapper}>
            <Image
              src="/images/me.jpg"
              width={100}
              height={100}
              layout="responsive"
              alt="me, the dev"
              className={`${classes.img} ${
                isAnimated && classes.animationSlideFromLeft
              }`}
            />
          </div>
        </div>
        <section>
          <TechStackList animation={isAnimated} />
        </section>
      </main>
    </>
  );
}
